config/routes.rb
Rails.application.routes.draw do
  root 'welcome#show'
  devise_for :users

  get 'users/:id/welcome', to: 'users#welcome', as: 'user_welcome'
  get 'users/:id/main', to: 'users#main', as: 'user_main'

  resources :users do
    resources :students
    resources :schools
  end

  resources :schools do
    resources :groups
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :students
  has_many :schools

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # def show
  #   @user = current_user
  #   if @user.save
  #     flash[:success] = 'Usuario registrado éxitosamente.'
  #     redirect_to user_show_path(current_user)
  #   else
  #     flash[:error] = @user.errors.full_messages.join(',')
  #     redirect_to new_user_session_path
  #   end
  # end
  def show
   @user = current_user
   if @user && @user.first_login
     current_user.update_attributes(first_login: false)
     redirect_to user_welcome_path(current_user)
   elsif @user && !@user.first_login
     redirect_to user_main_path(current_user)
   else
     redirect_to new_user_session_path
   end
 end


 # organizar para cuando un usuario no este logueado se muestre show
 # hacer una migracion para status booleano

 # def main
 #  @user = current_user
 #  #  if @user && @user.sign_in
 #  #    current_user.update_attributes(sign_in: true)
 #  #    redirect_to user_main_path(current_user)
 #  #  else
 #  #    redirect_to root_path(@user)
 #  #  end
 #  end

end

app/helpers/users_helper.rb
module UsersHelper
  # NOTE severly pushing the "clever" envelope here
  def differentiate_path(path, *args)
    attempt = request.parameters["attempt"]
    args.unshift(path).push(:attempt => attempt ? attempt.to_i + 1 : 1)
    send(*args)
  end

  # TODO move into application settings
  def status_icon_map
    { "out" => "delete",
      "in" => "check",
      "vacation" => "forward" }
  end
end

app/views/users/main.html.erb
<div data-role="header" class="user_status">
  <div class="row">
      <%= render partial: "layouts/header" %>
  </div>
</div>

<div data-role="content">

      <%= render partial: "layouts/orbe_menu" %>

  <div class="row add">
      <div class="user_add">
        <div>
          
        </div>
      </div>
      <div class="user_add">
        <!-- colocar link a school new -->
      </div>
      <div class="user_add">
        <!-- colocar link a school new -->
      </div>
      <div class="user_add">
        <!-- colocar link a school new -->
      </div>
  </div>

  <div class="row register">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
        <div class="delete_boton"><a href="#"></a></div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
      <center>
        <div class="ok_boton"><a href="#"></a></div>
      </center>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
      <center>
        <%= link_to "", new_user_school_path(current_user), class: "add_boton" %>
      </center>
    </div>
  </div>
</div>

app/views/users/show.html.erb
hola index
<div data-role="header" class="user_status">
  <div class="row">
      <%= render partial: "layouts/header" %>
  </div>
</div>

<div data-role="content">

      <%= render partial: "layouts/orbe_menu" %>

  <div class="row add">
      <div class="user_add">
        <div>

        </div>
      </div>
      <div class="user_add">
        <!-- colocar link a school new -->
      </div>
      <div class="user_add">
        <!-- colocar link a school new -->
      </div>
      <div class="user_add">
        <!-- colocar link a school new -->
      </div>
  </div>

  <div class="row register">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
        <div class="delete_boton"><a href="#"></a></div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
      <center>
        <div class="ok_boton"><a href="#"></a></div>
      </center>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
      <center>
        <%= link_to "", new_user_school_path(current_user), class: "add_boton" %>
      </center>
    </div>
  </div>
</div>

app/views/users/welcome.html.erb
<div data-role="header" class="user_status">
  <div class="row">
      <%= render partial: "layouts/header" %>
  </div>
</div>

<div data-content="content">

  <div class="row">
    <center>
      <div class="col-lg-12 col-md-12 col-sm-12 img5">
         <%= image_tag "orbe_index.png", :alt => "orbe", :title => "orbe"%>
      </div>
    </center>
  </div>

  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="mobile-nav2">
        <div class="menu-btn2" id="menu-btn2">
          <div>Bienvenido a Orbe <a href=""><%= image_tag "arrow_boton_down.png", :alt => "arrowd", :title => "arrowd"%></a></div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="responsive-menu2">
        <h1>Orbe es la aplicación en la que podrás hacer seguimiento a tus
          estudiantes con necesidades educativas especiales
          y adquirir conocimientos que te ayude a desenvolverte con ellos.</h1>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="mobile-nav2">
        <div class="menu-btn2" id="menu-btn2">
          <div>Nuestros pilares<a href=""><%= image_tag "arrow_boton_down.png", :alt => "arrowd", :title => "arrowd"%></a></div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="responsive-menu2">
        <h1>Orbe es la aplicación en la que podrás hacer seguimiento a tus
          estudiantes con necesidades educativas especiales
          y adquirir conocimientos que te ayude a desenvolverte con ellos.</h1>
      </div>
    </div>
  </div>
</div>