config/routes.rb
Rails.application.routes.draw do
  root 'welcome#show'
  devise_for :users

  get 'users/:id/welcome', to: 'users#welcome', as: 'user_welcome'
  get 'users/:id/main', to: 'users#main', as: 'user_main'

  resources :users do
    resources :students
    resources :schools
  end

  resources :schools do
    resources :groups
  end

end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= alert_class_for(type) %> alert-dismissible fade in">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="row">
  <div class="col-md-6 col-sm-6">
        Designed by
    <h1>Daniel Ochoa and Alejandro Agredo</h1>
  </div>
  <div class="col-md-6 col-sm-6">
        Development by
    <h1>Alejandro Serna</h1>
  </div>
</div>

</br>

<div class="row">
  <div class="col-md-6 col-sm-6">
        Contact us
    <h1>alejo.tanatos@gmail.com</h1>
    <h1>dikastidesign@gmail.com</h1>
    <h1>alejandrogom6@gmail.com</h1>
  </div>
  </br>
  <div class="col-md-6 col-sm-6">
        Orbe is a product of
    <h1>Brumker &trade;</h1>
  </div>
</div>

</br>

<div class="row">
  <div class="col-lg-12 col-md-12 col-sm-12">
    <center>
      &copy; All rights reserved &#8226; Orbe &trade;
    </center>
  </div>
</div>

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
  <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
    <h4>Conectado como</h4> <h3><%= current_user.email %></h3>
  </div>
  <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 text-2">
    <h2><%= link_to "Salir", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></h2>
    <h2><%= link_to 'Editar perfil', edit_user_registration_path, :class => 'navbar-link' %></h2>
  </div>
<% else %>
  <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 text-2">
    <h2><%= link_to "Registrarse", new_user_registration_path, :class => 'navbar-link' %></h2>
    <h2><%= link_to "Iniciar Sesión", new_user_session_path, :class => 'navbar-link' %></h2>
  </div>
<% end %>

app/views/layouts/_orbe_menu.html.erb
<div class="row">
  <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
    <div class="r-container">
      <%= link_to "", :back, class: "back"  %>
    </div>
  </div>
  <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
    <center>
     <%= image_tag "orbe_signup.png", class: "img4" %>
   </center>
  </div>
  <!-- menu hamburguesa -->
  <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
    <div class="mobile-nav">
      <div class="menu-btn" id="menu-btn">
        <div></div>
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>
  </div>

</div>

<div class="row">
  <div class="col-lg-12 col-md-12 col-sm-12">
    <!-- menu desplegado -->
    <div class="responsive-menu">
      <ul>
        <li>Instituciones</li>
        <li>Grupos</li>
        <li>Estudiantes</li>
      </ul>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-12 col-md-12 col-sm-12">
    <%= search_field(:user, :name) %>
  </div>
</div>

app/views/layouts/_user_menu.html.erb
<!-- Single button -->
<div class="btn-group">
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Menu <span class="caret"></span>
  </button>
  <ul class="dropdown-menu">
    <li><%= link_to "Vehicles", user_vehicles_path(current_user)%></li>
    <li><%= link_to "Reservations" %></li>
    <li><%= link_to "Account" %></li>
    <% if current_user.is_admin? %>
      <li><%= link_to "Users", users_path%></li>
      <li><%= link_to "Locations", locations_path%></li>
      <li><%= link_to "Settings" %></li>
      <li><%= link_to "History" %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Orbe</title>
  <meta name="keywords" content="Educación inclusiva, Educación de calidad, Autismo, Discapacidad auditiva, Colombia, Discapacidad cognitiva,">
  <meta name="description" content="Orbe, Una app en la educación inclusiva Colombiana.">


  <%= favicon_link_tag 'favicon.ico' %>

  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= stylesheet_link_tag "http://code.jquery.com/mobile/1.4.5/jquery.mobile.min.css", :media => "all" %>
  <%= javascript_include_tag "http://code.jquery.com/mobile/1.4.5/jquery.mobile.min.js" %>

  <%= csrf_meta_tags %>

</head>
<body class="ui-mobile-viewport container-fluid">
    <div data-role="page" class="wrapper" id="page1" data-dom-cache="true">
      
      <%= yield %>

    <div data-role="footer">
      <%= render partial: "layouts/footer" %>
    </div>
  </div>
</body>
</html>